name: Delete outdated deployments

on:
  schedule:
    - cron: "15 3 * * *"
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

jobs:
  delete-outdated-deployments:
    name: Delete outdated GitHub deployments
    runs-on: ubuntu-latest
    steps:
      - name: Delete outdated deployments
        uses: int128/delete-deployments-action@v1